export default  {
  ADD_PORTFOLIO: 'ADD_PORTFOLIO',
  DELETE_PORTFOLIO: 'DELETE_PORTFOLIO',

  ADD_STOCK: 'ADD_STOCK',
  UPDATE_STOCK_VALUES: 'UPDATE_STOCK_VALUES',
  DELETE_STOCKS: 'DELETE_STOCKS',

  CHANGE_TO_EUR: 'CHANGE_TO_EUR',
  CHANGE_TO_USD: 'CHANGE_TO_USD',

  GET_ERROR: 'GET_ERROR',
}
